defaults:
  resources:
    instance-type: P4000

jobs:
  CloneRepo:
    outputs:
      repo:
        type: dataset
        with:
          id: "dsrepfvwux4drca" #managed storage provider dataset
    uses: container@v1
    with:
      args:
      - clone
      - https://github.com/NVlabs/stylegan2.git 
      - /outputs/repo/stylegan2
      image: alpine/git

  StyleGan2:
    needs:
      - CloneRepo
    inputs: 
      repo: CloneRepo.outputs.repo
    outputs:
      generatedFaces:
        type: dataset
        with:
          id: "dsrepfvwux4drca" #managed storage provider dataset
    uses: container@v1
    with:
      args:
      - bash
      - -c
      - pip install scipy==1.3.3 && pip install requests==2.22.0 && pip install Pillow==6.2.1 
      - cp -R /inputs/repo/stylegan2 /stylegan2 && cd /stylegan2 && 
      - python run_generator.py generate-images --network=gdrive:networks/stylegan2-ffhq-config-f.pkl --seeds=6600-6605 --truncation-psi=0.5 --result-dir=/outputs/generatedFaces
      image: tensorflow/tensorflow:1.14.0-gpu-py3
