# StyleGAN example workflow
# Uses its cat model & dataset because faces download was too big
#
# TODO
#
# Between steps 4 and 5, show running training in addition to evaluation
# Any "###" items below
#
# Steps:
#
# 1. Clone StyleGAN repo into managed storage provider dataset
# 2. Get pretrained cat model into same dataset
# 3. Show generating images using pretrained cat model
# 4. Clone cat subsample image data repo to enable evaluating the network
# 5. Run evaluation using pretrained cat model on cat subsample dataset
#
# Last updated: Apr 20th 2021

# "name" keyword not used - causes error

defaults:
  resources:
    instance-type: P4000

jobs:

  # 1. Clone StyleGAN repo into managed storage provider dataset

  # ID is from creating this dataset in the Gradient Workflows GUI

  CloneRepo:
    outputs:
      repo:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg"
    uses: container@v1
    with:
      args:
      - clone
      - https://github.com/NVlabs/stylegan2.git
      - /outputs/repo/stylegan2
      image: alpine/git

  # 2. Get pretrained cat model into same dataset

  # Model .pkl is large so is not in the above repo
  # Copies .pkl in this step, then refer to the ID:version below to acoid copying it again in the next steps

  GetPretrainedModel:
    outputs:
      pretrainedNetwork:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg"
    uses: container@v1
    with:
      args:
      - wget
      - https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/stylegan2-cat-config-f.pkl
      - -P
      - /outputs/pretrainedNetwork
      image: alpine:latest

  # 3. Show generating images using pretrained cat model

  StyleGan2:
    needs:
      - CloneRepo
      - GetPretrainedModel
    inputs:
      repo: CloneRepo.outputs.repo
      pretrainedNetwork:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg:a1edfdv"
    outputs:
#      generatedFaces:
      generatedCats:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg"
    uses: container@v1
    with:
      args:
      - bash
      - -c
#      - pip install scipy==1.3.3 && pip install requests==2.22.0 && pip install Pillow==6.2.1 && cp -R /inputs/repo/stylegan2 /stylegan2 && cd /stylegan2 && python run_generator.py generate-images --network=/inputs/repo/stylegan2-ffhq-config-f.pkl --seeds=6600-6605 --truncation-psi=0.5 --result-dir=/outputs/generatedFaces
      - pip install scipy==1.3.3 && pip install requests==2.22.0 && pip install Pillow==6.2.1 && cp -R /inputs/repo/stylegan2 /stylegan2 && cd /stylegan2 && python run_generator.py generate-images --network=/inputs/pretrainedNetwork/stylegan2-cat-config-f.pkl --seeds=6600-6605 --truncation-psi=0.5 --result-dir=/outputs/generatedCats
      image: tensorflow/tensorflow:1.14.0-gpu-py3

  # 4. Clone cat subsample image data repo to enable training and evaluating the network

  # Use git-checkout action so can pass my Git Token as a secret
  # Managed storage provider dataset was created by GUI even though auth failed (bug), so use the ID
  # Checkout results in output volume, so don't need "outputs:" field

  CloneCatRepo:
    inputs:
      repoCat:
        type: volume
#    outputs:
#      repo:
#        type: dataset
#        with:
#          id: "dstaxp1zuggbxp0"
    uses: git-checkout@v1
    with:
      url: https://github.com/nmb-paperspace/cat-subsample
      username: nmb-paperspace
#      image: alpine/git
    env:
      GIT_PASSWORD: secret:GIT_PASSWORD
#    uses: container@v1
#    with:
#      args:
#      - clone
#      - https://github.com/nmb-paperspace/cat-subsample
#      - /outputs/repoCat/cat-subsample

  # 4.5 (TODO) Train the network on image subsample

  # Extendable in principle to entire image set if this works

  ### The new model action might be relevant: "FYI we've updated the Workflows spec to remove model input/output and move it into it's own action. The removal was just merged and Erika is QAing a new action to support model generation. This lets our spec be less prescriptive(?) and have the logic live in an action where we can more easily evolve it. We'll be updating the docs to make this more clear during this weeks cooldown cc: @dillon" ###

#  StyleGan2Train:
#    needs:
#      - CloneRepo
#      - CloneCatRepo
#    inputs:
#      repoCat:
#        type: volume
#      repo: CloneRepo.outputs.repo
#    outputs:
#      trainedNetwork:
#        type: dataset
#        with:
#          id: "dsrydbkw4yf7tlg"
#    uses: container@v1
#    with:
#      args:
#        - bash
#        - -c
#        - echo hello
##        - pip install scipy==1.3.3 && pip install requests==2.22.0 && pip install Pillow==6.2.1 && cp -R /inputs/repo/stylegan2 /stylegan2 && cd /stylegan2 && tar -zxf /inputs/repoCat/cat_images_017.tgz && python run_training.py --num-gpus=1 --data-dir=/inputs/repoCat/cat_images_017 --config=config-f --dataset=cat --total-kimg=88000 --result-dir=/outputs/training
#      image: tensorflow/tensorflow:1.14.0-gpu-py3

  # 5. Run evaluation using pretrained cat model on cat subsample dataset

  ### Way to make the bash command separate lines for readability? (">" is available, but args has "-" too) ###

  StyleGan2Eval:
    needs:
      - CloneRepo
      - CloneCatRepo
      - GetPretrainedModel
#      - StyleGan2Train # TODO: When train is running, can take its network as input
    inputs:
      repoCat:
        type: volume
      repo: CloneRepo.outputs.repo
#      repoCat: CloneCatRepo.outputs.repoCat
#      pretrainedNetwork: GetPretrainedModel.outputs.pretrainedNetwork
      pretrainedNetwork:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg:a1edfdv"
    outputs:
      evaluation:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg"
    uses: container@v1
    with:
      args:
      - bash
      - -c
      - "pip install scipy==1.3.3 && pip install requests==2.22.0 && pip install Pillow==6.2.1 && cp -R /inputs/repo/stylegan2 /stylegan2 && cd /stylegan2 && tar -zxf /inputs/repoCat/cat_images_017.tgz; sleep 10; ls /inputs/repoCat"
#      - && python run_metrics.py --data-dir=/inputs/repoCat/cat_images_017 --network=/inputs/pretrainedNetwork/stylegan2-cat-config-f.pkl --metrics=fid50k,ppl2_wend --dataset=cat --result-dir=/outputs/evaluation
      image: tensorflow/tensorflow:1.14.0-gpu-py3
