defaults:
  resources:
    instance-type: P4000

jobs:
  CloneRepo:
    outputs:
      repo:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg" #managed storage provider dataset
    uses: container@v1
    with:
      args:
      - clone
      - https://github.com/NVlabs/stylegan2.git 
      - /outputs/repo/stylegan2
      image: alpine/git

  GetPretrainedModel:
    outputs:
      pretrainedNetwork:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg" #managed storage provider dataset
    uses: container@v1
    with:
      args:
      - wget
      - https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/stylegan2-ffhq-config-f.pkl
      - -P
      - /outputs/pretrainedNetwork
      image: alpine:latest

  StyleGan2:
    needs:
      - CloneRepo
      - GetPretrainedModel
    inputs: 
      repo: CloneRepo.outputs.repo
      pretrainedNetwork: GetPretrainedModel.outputs.pretrainedNetwork
    outputs:
      styleMixing:
        type: dataset
        with:
          id: "dsrydbkw4yf7tlg" #managed storage provider dataset
    uses: container@v1
    with:
      args:
      - bash
      - -c
      - pip install scipy==1.3.3 && pip install requests==2.22.0 && pip install Pillow==6.2.1 && cp -R /inputs/repo/stylegan2 /stylegan2 && cd /stylegan2 && python run_generator.py style-mixing-example --network=/inputs/pretrainedNetwork/stylegan2-ffhq-config-f.pkl --row-seeds=85,100,75,458,1500 --col-seeds=55,821,1789,293 --truncation-psi=1.0 --result-dir=/outputs/styleMixing
      image: tensorflow/tensorflow:1.14.0-gpu-py3
